#ifndef _COMMON_CORE_ERRORCODE_H_
#define _COMMON_CORE_ERRORCODE_H_

#define ERR_CORE_SERVER_CREATE_NEW_BASE         1
#define ERR_CORE_SERVER_CREATE_NEW_LISTENER     2
#define ERR_CORE_SERVER_START_DAEMON            3
#define ERR_CORE_SERVER_ONREAD_NO_CLIENT        4 
#define ERR_CORE_SERVER_ONERROR_ACTIVE_CLOSED   5 
#define ERR_CORE_SERVER_ONERROR_CLIENT_RESET    6 
#define ERR_CORE_SERVER_ONERROR_CLIENT_READING  7 
#define ERR_CORE_SERVER_ONERROR_CLIENT_WRITING  8 
#define ERR_CORE_SERVER_ONERROR_CLIENT_TIMEOUT  9
#define ERR_CORE_SERVER_ACCEPT_CLIENT_MAX       10
#define ERR_CORE_SERVER_ACCEPT_FD_HAD_CLINET    11
#define ERR_CORE_SERVER_ACCEPT_NO_EVENT_BASE    12
#define ERR_CORE_SERVER_ACCEPT_CREATE_BUFFER    13
#define ERR_CORE_SERVER_HTTP_HTTP_NEW           14
#define ERR_CORE_SERVER_HTTP_BIND_SOCKET        15

#define ERR_CORE_CLINET_CONNECT_TYPE            41
#define ERR_CORE_CLINET_CONNECT_WITH_BUFFER     42
#define ERR_CORE_CLINET_CONNECT_FAILED          43
#define ERR_CORE_CLINET_READ_PARAM              44
#define ERR_CORE_CLINET_READ_NO_BUFF            45
#define ERR_CORE_CLINET_READ_BUFF_COPY          46
#define ERR_CORE_CLINET_READ_MSG_SIZE_ZERO      47
#define ERR_CORE_CLINET_READ_MSG_SIZE_OVERFLOW  48
#define ERR_CORE_CLINET_READ_BUFF_DRAIN         49
#define ERR_CORE_CLINET_WRITE_PARAM             50
#define ERR_CORE_CLINET_WRITE_MSG_SIZE_OVERFLOW 51
#define ERR_CORE_CLINET_WRITE_FAILED            52
#define ERR_CORE_CLINET_WRITE_ENCODE            53

#endif
